# Practice makefile using a couple common things

CC=g++
cflags=-Wall
rmflags=-rf

all:
	$(CC) $(cflags) pixieParser.cpp -o pixieParser

clean:
	rm $(rmflags) pixieParser
	rm $(rmflags) Proximity_scan_120814_0042.txt
